### ISSUE TITLE
Windows Defender found Trojan

### ISSUE THREAD

**Issue by ozgurg** [runletapp/runlet#1]
Windows Defender found Trojan.

Details:
![Screenshot_1](https://user-images.githubusercontent.com/6717356/79688021-da9f7080-8253-11ea-86cb-0005775bcfb6.png)

**Comment by vandreleal** [comment]
Hi @ozgurg ,

Thanks for letting us know. Unfortunately, Microsoft Defender is incorrectly flagging the uninstaller of Electron apps built with electron-builder as pointed by other developers at [https://github.com/electron-userland/electron-builder/issues/4793](https://github.com/electron-userland/electron-builder/issues/4793). We are working on a fix for the next version.
