### ISSUE TITLE
local task should not connect to the cloud

### ISSUE THREAD

**Issue by n-for-all** [runletapp/runlet#2]
This app idea is very good, i am looking for something to automate the tasks locally and across devices and this app works quite well but lags a lot, i guess because it is connecting to the cloud each time it excutes a task

**Is your feature request related to a problem? Please describe.**
Pending status cannot be cancelled, whatever i do, it gets stuck untill it timesout, even restarting the app doesn't fix the issue

**Describe the solution you'd like**
- Execute local task without connecting to the cloud, directly on terminal
- Adding reminders because some requires manuall execution
- Async execution

**Describe alternatives you've considered**
I haven't found any alternative for this app

**Additional context**
none

**Comment by GustavoKatel** [comment]
hi @n-for-all thanks for the suggestions we are aligned with that and in fact we are currently working on the version 2, which will solve most of the issues you pointed out + some new cool features 😄
