### ISSUE TITLE
No longer works on macos 12.3.1 [BUG]

### ISSUE THREAD

**Issue by n-for-all** [runletapp/runlet#3]
When i try to run runlet from the contents directory, it show an error with python not found, could be this is related
https://macmule.com/2022/01/29/macos-monterey-12-3-will-remove-python-2-7-usr-bin-python/

How can i fix it?

**Comment by vandreleal** [comment]
Hi @n-for-all , thanks for letting us know. We will take a look soon and let you know.

**Comment by vandreleal** [comment]
Hi @n-for-all . i've just published a new version that addresses that issue 👍🏽  https://github.com/runletapp/runlet/releases/tag/1.0.7. Thanks for letting us know and apologies for the delay in response. This is a side-project that we aren't able to put a lot of effort at the moment. Keep us posted if you have any issues, please.
